name: IaC Deploy

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to deploy (dev, test, prod)"
                required: true
                default: dev
                type: choice
                options:
                    - dev
                    - test
                    - prod

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
            APP_NAME: techtest-app
            LOCATION: uksouth
            ENVIRONMENT: ${{ github.event.inputs.environment }}
            RESOURCE_GROUP: techtest-rg${{ github.event.inputs.environment == 'prod' && '' || format('-{0}', github.event.inputs.environment) }}

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Create resource group (if not exists)
              run: |
                  az group create \
                    --name $RESOURCE_GROUP \
                    --location $LOCATION

            - name: Deploy Bicep file
              uses: azure/cli@v1
              with:
                  inlineScript: |
                      az deployment group create \
                        --name iac-deploy-${{ github.run_number }} \
                        --resource-group $RESOURCE_GROUP \
                        --template-file infrastructure/main.bicep \
                        --parameters appName=$APP_NAME \
                                     environment=$ENVIRONMENT \
                                     location=$LOCATION
