name: IaC Deploy

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
            RESOURCE_GROUP: Tech_Test
            LOCATION: uksouth

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Create resource group (if not exists)
              run: |
                  az group create \
                    --name $RESOURCE_GROUP \
                    --location $LOCATION

            - name: Deploy Bicep file
              uses: azure/cli@v1
              with:
                  inlineScript: |
                      az deployment group create \
                        --name iac-deploy-${{ github.run_number }} \
                        --resource-group $RESOURCE_GROUP \
                        --template-file infrastructure/main.bicep \
                        --parameters appName=techtest-app environment=dev location=$LOCATION
