name: IaC Deploy

on:
  workflow_dispatch: # manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/cli@v1
      with:
        inlineScript: |
          az deployment group create \
            --resource-group Tech_Test \
            --template-file infrastructure/main.bicep \
            --parameters appName=techtest-app
